import type { WebPackInfo } from "./webpacks";

export const WEB_DEFAULT_PACK = "holy-panda";

/** One line on each pack's character, shown on its card. */
export const BLURBS: Record<string, string> = {
  "cherry-mx-black-abs": "Heavy, smooth, low",
  "cherry-mx-black-pbt": "Heavy, smooth, deeper",
  "cherry-mx-red-abs": "Light and quick",
  "cherry-mx-red-pbt": "Light, quick, rounder",
  "gateron-black-ink": "Deep and silky",
  "gateron-red-ink": "Bright and silky",
  "novelkeys-cream": "Warm and marbly",
  alpaca: "Soft and poppy",
  "turquoise-tealios": "Clean and even",
  "cherry-mx-brown-abs": "A gentle bump",
  "cherry-mx-brown-pbt": "A gentle bump, fuller",
  "holy-panda": "Rounded thock",
  topre: "Cushioned thock",
  "topre-purple-hybrid-pbt": "Deep, damped thock",
  "everglide-crystal-purple": "Bright and snappy",
  "everglide-oreo": "Punchy and dense",
  "cherry-mx-blue-abs": "Crisp, loud click",
  "cherry-mx-blue-pbt": "Crisp click, fuller",
  "kailh-box-navy": "Heavy, sharp click",
  "skcm-blue-alps": "Vintage Alps chatter",
  "buckling-spring": "The IBM Model M",
};

const GROUPS = [
  ["linear", "Linear"],
  ["tactile", "Tactile"],
  ["clicky", "Clicky"],
] as const;

export function escapeHtml(text: string): string {
  const map: Record<string, string> = { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" };
  return text.replace(/[&<>"']/g, (c) => map[c]!);
}

const label = (p: WebPackInfo) => (p.variant ? `${p.name} (${p.variant})` : p.name);
const categoryName = (c: string) => GROUPS.find(([id]) => id === c)?.[1] ?? "Other";

export function renderPackCards(packs: WebPackInfo[], selected: string): string {
  return packs
    .map(
      (p) => `
<li class="pack-card" data-pack="${p.id}" data-category="${p.category}">
  <button type="button" class="pack-card__button" aria-pressed="${p.id === selected}" data-select-pack="${p.id}">
    <span class="keycap" style="--cap: ${p.color}" aria-hidden="true"></span>
    <span class="pack-card__text">
      <span class="pack-card__name">${escapeHtml(p.name)}${p.variant ? ` <span class="chip">${escapeHtml(p.variant)}</span>` : ""}</span>
      <span class="pack-card__meta">${categoryName(p.category)} · ${escapeHtml(BLURBS[p.id] ?? "")}</span>
    </span>
    <span class="pack-card__play" aria-hidden="true"></span>
  </button>
</li>`,
    )
    .join("");
}

export function renderMenuPacks(packs: WebPackInfo[], selected: string): string {
  return GROUPS.map(([id, name]) => {
    const items = packs
      .filter((p) => p.category === id)
      .map(
        (p) => `
<button type="button" class="menu__item menu__pack" role="menuitemradio" aria-checked="${p.id === selected}" data-select-pack="${p.id}">
  <span class="keycap keycap--small" style="--cap: ${p.color}" aria-hidden="true"></span>${escapeHtml(label(p))}
</button>`,
      )
      .join("");
    return `<div class="menu__group" role="group" aria-label="${name}"><div class="menu__heading">${name}</div>${items}</div>`;
  }).join("");
}

export function renderPackOptions(packs: WebPackInfo[], selected: string): string {
  return GROUPS.map(
    ([id, name]) =>
      `<optgroup label="${name}">${packs
        .filter((p) => p.category === id)
        .map((p) => `<option value="${p.id}"${p.id === selected ? " selected" : ""}>${escapeHtml(label(p))}</option>`)
        .join("")}</optgroup>`,
  ).join("");
}

export function renderJsonLd(): string {
  const data = {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: "Rustyvibes",
    operatingSystem: "macOS 13 or later",
    applicationCategory: "UtilitiesApplication",
    description:
      "Real mechanical keyboard sounds for every key you press, in every app. A tiny, native menu bar app for Mac.",
    url: "https://rustyvibes.kunalbagaria.com/",
    offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
    author: { "@type": "Person", name: "Kunal Bagaria" },
  };
  return `<script type="application/ld+json">${JSON.stringify(data).replace(/</g, "\\u003c")}</script>`;
}

export function renderPartials(packs: WebPackInfo[], selected: string): Record<string, string> {
  return {
    "pack-cards": renderPackCards(packs, selected),
    "menu-packs": renderMenuPacks(packs, selected),
    "pack-options": renderPackOptions(packs, selected),
    "json-ld": renderJsonLd(),
  };
}

export function catalogModule(packs: WebPackInfo[], selected: string): string {
  const rows = packs.map((p) =>
    JSON.stringify({
      id: p.id,
      name: p.name,
      variant: p.variant,
      category: p.category,
      color: p.color,
      url: p.url,
      bytes: p.bytes,
      hasRelease: p.hasRelease,
    }),
  );
  return `// Generated by scripts/build.ts. Do not edit.
export interface PackInfo { id: string; name: string; variant: string; category: string; color: string; url: string; bytes: number; hasRelease: boolean }
export const PACKS: readonly PackInfo[] = [
${rows.map((r) => `  ${r},`).join("\n")}
];
export const DEFAULT_PACK = ${JSON.stringify(selected)};
`;
}
